language: bash
services: docker

env:
  - VERSION=8.5-rc VARIANT=apache
  - VERSION=8.5-rc VARIANT=fpm
  - VERSION=8.5-rc VARIANT=fpm-alpine
  - VERSION=8.4 VARIANT=apache
  - VERSION=8.4 VARIANT=fpm
  - VERSION=8.4 VARIANT=fpm-alpine
  - VERSION=7 VARIANT=apache
  - VERSION=7 VARIANT=fpm
  - VERSION=7 VARIANT=fpm-alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION/$VARIANT"
  - slash='/'; image="docker-drupal:$VERSION-${VARIANT//$slash/-}"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
